# Generated by Django 3.0.5 on 2020-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Outdoor'), ('Out door', 'Out door')], max_length=200, null=True),
        ),
    ]
